---
sidebar: sidebar
permalink: oci/add-credentials-oci.html
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials, oci nss, oracle cloud infrastructure
summary: "Add Oracle Cloud Infrastructure (OCI) credentials so that Workload Factory has the permissions that it needs to deploy and manage cloud resources in your OCI accounts."
---
= Add Oracle Cloud Infrastructure credentials to NetApp Workload Factory
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Add and manage your cloud provider credentials so that NetApp Workload Factory has the permissions that it needs to deploy and manage resources in your cloud provider accounts. 

link:permissions-oci.html[Permissions for OCI NetApp Storage Service]

.About this task

You can add credentials to an existing Workload Factory account from the Credentials page. This provides Workload Factory with the permissions needed to manage resources and processes within your cloud environment.

.Before you begin

You'll need to have credentials to log in to your Oracle Cloud Infrastructure account.

.Steps

. Log in to the https://console.netapp.com/[NetApp console^].
. From the menu, select *Workloads* > *Administration* > *Credentials*.
. On the Credentials page, select *Add credentials*.
. On the Add Oracle Cloud Infrastructure NetApp Storage Service credentials page, do the following:
.. Under _Permissions configuration_, select the appropriate permissions for the Oracle Cloud Infrastructure NetApp Storage Service credentials. *View, plan, and analyze* permissions are the default. This permission policy allows you to view OCI NSS storage pools, learn about system health, get the well-architected analysis for your systems, and explore savings.
.. Follow the manual steps provided using the Oracle Cloud Console to complete the permissions configuration for the OCI NSS credentials.
.. Under _Credentials name_, enter the name that you want to use for these credentials and enter the Tenancy OCID.
. Select *Add*. 

.What's next

link:quick-start-oci.html[Quick start for Oracle Cloud Infrastructure NetApp Storage Service in NetApp Workload Factory.]