---
sidebar: sidebar
permalink: oci/learn-about-oci.html
keywords: Oracle Cloud Infrastructure NetApp Storage Service
Oracle Cloud Infrastructure NetApp Storage Service, OCI NetApp Storage Service, Oracle Cloud storage, storage, oci nss
summary: "OCI NetApp Storage Service is a fully managed service allowing customers to create and manage storage pools as the storage backend for your workloads within Workload Factory." 
---
= Learn about OCI NetApp Storage Service in NetApp Workload Factory
:icons: font
:imagesdir: ../media/

[.lead]
Oracle Cloud Infrastructure (OCI) NetApp Storage Service is a fully managed, cloud-based data storage service that provides advanced data management capabilities and highly scalable performance. OCI NetApp Storage Service allows you to create and manage storage pools as the storage backend for all your workloads within NetApp Workload Factory. 

OCI NetApp Storage Service provides the same features, performance, and administrative capabilities NetApp customers use on premises today, with the simplicity, agility, security, and scalability of a native Oracle Cloud service.

OCI NetApp Storage Service is the _Storage_ component in Workload Factory.

== Features
OCI NetApp Storage Service offers the following features:

* *Fully-managed service*: provides a fully-managed service integrated with the Workload Factory console. 
* *High availability*: provides high availability for each OCI NetApp Storage Service storage pool, supporting Single and Multiple Availability Zones deployments. 
* *Automated snapshots*: protects data with automated, efficient snapshots, which are near instantaneous, space efficient point-in-time read-only copies of the storage pool or volumes. 
* *Volume replication*: provides disaster recovery with cross-region replication across Oracle Cloud Infrastructure. 
* *Efficient backups*: adds an extra layer of protection with a copy of the data in another region for emergencies.
* *Fast cloning*: accelerates application development with fast cloning.
* *Multi-protocol support*: supports Network File System (NFS), Server Message Block (SMB), and Internet Small Computer Systems Interface (iSCSI) protocols. 
* *High throughput*: delivers high throughput performance to ensure low latencies for workloads running on top of OCI NetApp Storage Service file systems. 
* *In-memory cache and NVMe cache*: includes a unique in-memory cache and NVMe cache, which boosts the performance of frequently accessed data.
* *Hundreds of thousands of IOPS*: provides hundreds of thousands of IOPS with SSD disks, ensuring that your storage and workloads receive timely results.
* *Thin Provisioning*: allows capacity provisioning in advance, saving costs until more capacity is needed.  
* *Data deduplication and compression*: removes duplicate data and compresses data to reduce the amount of physical storage that is required for OCI NetApp Storage Service file systems resulting in cost savings. 
* *Data tiering*: allows storage cost reduction by moving less frequently accessed data from the primary, high performance SSD storage tier to the secondary capacity pool storage tier. 

== Tools to use NetApp Workload Factory
You can use NetApp Workload Factory with the following tools:

* *Workload Factory console*: The Workload Factory console provides a visual, holistic view of your applications and projects.
* *NetApp Console*: The NetApp Console provides a hybrid interface experience so that you can use Workload Factory along with other NetApp data services.
* *Ask Me*: Use the Ask Me AI assistant to ask questions and learn more about Workload Factory without leaving the Workload Factory console. Access Ask Me from the Workload Factory user interface.
* *CloudShell CLI*: Workload Factory includes a CloudShell CLI to manage and operate AWS and NetApp environments across accounts from a single, browser-based CLI. Access CloudShell from the top bar of the Workload Factory console.
* *REST API*: Use the Workload Factory REST APIs to deploy and manage your OCI NetApp Storage Service systems and other OCI NetApp Storage Service resources.
* *Oracle Cloud Infrastructure (OCI) Resource Manager*: Use OCI Resource Manager to perform the actions you defined in the Workload Factory console to model, provision, and manage OCI and third-party resources from the Resource Manager stack in your OCI account.
* *NetApp Terraform provider*: Use Terraform to build and manage infrastructure workflows generated in the Workload Factory console.

== Getting help
For general questions about Workload Factory or Workload Factory applications and services, refer to link:get-help.html[Get help for OCI NetApp Storage Service for Workload Factory].