settings:
  name: Workload Factory for NetApp Console
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"  
  release_notes_autogen:
    release_notes_repo: console-relnotes
sidebar: 
  entries:
    - title: Workload Factory for NetApp Console
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /release-notes/whats-new.html
        - title: Known limitations
          url: /release-notes/known-limitations.html
    - title: Get started
      entries:
        - title: Learn about Workload Factory in NetApp Console
          url: /setup/learn-workload-factory.html
        - title: Quick start
          url: /setup/quick-start.html
        - title: Sign up and log in to Workload Factory
          url: /setup/sign-up-log-in-saas.html 
        - title: Learn about links
          url: /setup/links-overview.html
        - title: Learn about permissions
          url: /setup/learn-about-permissions.html
    - title: Amazon FSx for NetApp ONTAP
      entries:
        - title: Use FSx for ONTAP for storage workloads
          entries: 
            - title: Learn about FSx for ONTAP
              url: /fsx/learn-fsx-ontap-fsx.html
            - title: Explore savings
              url: /fsx/explore-savings-fsx.html
            - title: Create storage resources
              entries: 
                - title: Create an FSx for ONTAP file system
                  url: /fsx/create-file-system-fsx.html
                - title: Create a storage VM
                  url: /fsx/create-storage-vm-fsx.html
                - title: Create a volume
                  url: /fsx/create-volume-fsx.html
                - title: Create an igroup
                  url: /fsx/create-igroup-fsx.html
                - title: Create a block device  
                  url: /fsx/create-block-device-fsx.html
            - title: Learn about links
              url: /fsx/learn-about-links-fsx.html
            - title: Discover and view cache volumes
              url: /fsx/discover-cache-volumes-fsx.html
            - title: Access your data
              url: /fsx/access-data-fsx.html
        - title: Protect your data
          entries:
            - title: Data protection overview 
              url: /fsx/data-protection-overview-fsx.html
            - title: Use snapshots to protect data
              entries: 
                - title: Use snapshots to protect data
                  url: /fsx/use-snapshots-fsx.html
                - title: Manage snapshot policies
                  url: /fsx/manage-snapshot-policy-fsx.html
                - title: Manage snapshots
                  url: /fsx/manage-snapshots-fsx.html    
            - title: Use backups to object storage
              url: /fsx/use-backups-fsx.html
            - title: Use replication to protect data
              entries: 
                - title: Replicate data
                  url: /fsx/create-replication-fsx.html
                - title: Replicate on-premises ONTAP data to FSx for ONTAP
                  url: /fsx/use-onprem-data-fsx.html              
                - title: Replicate a storage VM to another file system
                  url: /fsx/replicate-svm-to-file-system-fsx.html              
                - title: Track replication delays
                  url: /fsx/track-replication-delays-fsx.html  
                - title: Manage replication relationships
                  url: /fsx/manage-replication-fsx.html  
            - title: Protect data with Autonomous Ransomware Protection
              url: /fsx/ransomware-protection-fsx.html   
            - title: Clone a volume
              url: /fsx/clone-volume-fsx.html  
            - title: Create a cyber vault to protect data
              url: /fsx/create-cyber-vault-fsx.html  
        - title: Manage FSx for ONTAP in Workload Factory
          entries:
            - title: Analyze FSx for ONTAP EMS events      
              url: /fsx/analyze-events-fsx.html
            - title: Implement file system best practices
              entries: 
                - title: Configuration analysis for FSx for ONTAP
                  url: /fsx/configuration-analysis-fsx.html
                - title: Implement well-architected file system configurations
                  url: /fsx/improve-configurations-fsx.html 
            - title: Track and analyze FSx for ONTAP costs
              url: /fsx/track-costs-fsx.html           
            - title: Manage volumes
              entries:  
                - title: Manage volume capacity
                  url: /fsx/manage-volume-capacity-fsx.html
                - title: Set volume latency thresholds
                  url: /fsx/set-volume-latency-thresholds-fsx.html
                - title: Manage volume settings
                  url: /fsx/manage-volume-settings-fsx.html  
                - title: Manage cache volumes
                  url: /fsx/manage-cache-volumes-fsx.html
                - title: Change a tiering policy
                  url: /fsx/change-tiering-policy-fsx.html   
                - title: Manage NFS export policies
                  url: /fsx/manage-nfs-export-policy-fsx.html  
                - title: Manage SMB/CIFS shares
                  url: /fsx/manage-cifs-share-fsx.html 
                - title: Manage S3 access points 
                  entries: 
                    - title: Create and attach S3 access points
                      url: /fsx/create-s3-access-points-fsx.html
                    - title: Edit S3 access points
                      url: /fsx/edit-s3-access-points-fsx.html
                    - title: Set up the journal table infrastructure
                      url: /fsx/setup-journal-table-fsx.html
                    - title: View details about S3 access points
                      url: /fsx/view-s3-details-fsx.html
                    - title: Delete S3 access points
                      url: /fsx/delete-s3-access-points-fsx.html           
                - title: Split a cloned volume
                  url: /fsx/split-cloned-volume-fsx.html    
                - title: Delete a volume
                  url: /fsx/delete-volume-fsx.html
            - title: Manage block storage
              entries:
                - title: Manage block storage
                  url: /fsx/manage-block-storage-fsx.html
                - title: Apply tags to block devices
                  url: /fsx/apply-block-device-tags-fsx.html  
            - title: Manage file systems
              entries: 
                - title: Adjust file system capacity
                  url: /fsx/adjust-file-system-capacity-fsx.html
                - title: Manage file system settings
                  url: /fsx/manage-file-system-settings-fsx.html
                - title: Provision IOPS for a file system
                  url: /fsx/provision-iops-fsx.html              
                - title: Delete a file system
                  url: /fsx/delete-file-system-fsx.html
            - title: Manage storage VMs
              entries: 
                - title: Manage storage VM settings
                  url: /fsx/manage-svm-settings-fsx.html
                - title: Delete a storage VM 
                  url: /fsx/delete-svm-fsx.html
            - title: Monitor operations with Tracker
              url: /fsx/monitor-operations-fsx.html       
        - title: Reference
          entries: 
            - title: Performance for FSx for ONTAP
              url: /fsx/performance-reference-fsx.html
            - title: Security for FSx for ONTAP
              url: /fsx/security-reference-fsx.html   
        - title: Use FSx for ONTAP for database workloads
          entries:
            - title: Explore savings
              url: /explore-savings.html
            - title: Create a new database server
              entries:
                - title: Create Microsoft SQL Server    
                  url: /create-database-server.html
                - title: Create PostgreSQL server
                  url: /create-postgresql-server.html  
            - title: Manage resources
              entries: 
                - title: Resource management
                  url: /manage-instance.html
                - title: Register resources
                  url: /register-instance.html
                - title: Create a database
                  url: /create-database.html 
                - title: Create a sandbox clone 
                  url: /create-sandbox-clone.html                       
                - title: Protect Microsoft SQL Server workloads
                  url: /protect-sql-server.html   
            - title: Administer and monitor FSx for ONTAP for database workloads
              entries:
                - title: Monitor database jobs
                  url: /monitor-databases.html
                - title: Implement configuration best practices
                  entries: 
                    - title: Configuration analysis for Databases
                      url: /optimize-overview.html
                    - title: Implement well-architected database configurations   
                      url: /optimize-configurations.html     
                - title: Analyze error logs
                  url: /analyze-error-logs.html
            - title: Manage clones
              entries: 
                - title: Check integrity of a sandbox clone
                  url: /check-clone-integrity.html  
                - title: Revert a sandbox clone
                  url: /revert-clone.html 
                - title: Refresh a sandbox clone
                  url: /refresh-clone.html  
                - title: Connect to the CI/CD pipeline
                  url: /connect-clone-cicd.html  
                - title: View clone connection information
                  url: /view-clone-connection.html  
                - title: Split a sandbox clone
                  url: /split-clone.html  
                - title: Delete a sandbox clone
                  url: /delete-clone.html                                 
                - title: Deregister resources
                  url: /deregister-instance.html           
        - title: Use FSx for ONTAP for EDA workloads
          entries:   
             - title: Learn about NetApp Workload Factory for EDA
               url: /learn-eda.html 
             - title: Quick start
               url: /quick-start-eda.html
             - title: Requirements
               url: /requirements-eda.html
             - title: EDA storage overview
               entries:
                 - title: Learn about the Overview dashboard
                   url: /learn-overview-dashboard.html
                 - title: Activate the Overview dashboard
                   url: /task-activate-overview-dashboard.html
                 - title: Use the Overview dashboard
                   url: /task-use-overview-dashboard.html
             - title: Project usage analysis
               entries:
                 - title: Learn about the Projects dashboard
                   url: /learn-project-dashboard.html
                 - title: Configure the Projects dashboard
                   url: /task-configure-project-dashboard.html
                 - title: Use the Projects dashboard
                   url: /task-use-project-dashboard.html
             - title: Use Perforce integration
               entries: 
                  - title: Learn about Perforce integration
                    url: /learn-eda-workloads.html
                  - title: Manage projects
                    url: /manage-projects.html
                  - title: Manage project versions
                    url: /version-projects.html
                  - title: Create a workspace
                    url: /create-workspaces.html
                  - title: Automate with Codebox
                    url: /automate-codebox.html
                  - title: Integrate with Perforce
                    url: /integrate-perforce.html
        - title: Use Amazon FSx for NetApp ONTAP for VMware workloads
          entries:                   
            - title: Learn about NetApp Workload Factory for VMware
              url: /learn-about-vmware-workloads.html
            - title: Quick start for migrating to Amazon EVS
              url: /quick-start-evs.html        
            - title: Quick start for migrating to Amazon EC2
              url: /quick-start-native.html
            - title: Quick start for migrating to VMware Cloud on AWS
              url: /quick-start.html
            - title: Quick start for migrating to Google Cloud VMware Engine
              url: /quick-start-gcve.html
            - title: Explore the VMware planning center
              url: /explore-planning-center.html
            - title: Use the VMware planning center
              entries:
                - title: Upload VM inventory data
                  url: /upload-vm-inventory.html
                - title: Migrate to Amazon Elastic VMware Service
                  entries:
                    - title: Explore savings
                      url: /calculate-evs-savings.html
                    - title: Manually create a deployment plan
                      url: /launch-migration-advisor-evs-manual.html
                    - title: Create a deployment plan using the migration advisor
                      url: /launch-migration-advisor-evs.html
                    - title: Deploy the recommended FSx for ONTAP file system
                      url: /deploy-fsx-file-system-evs.html
                - title: Migrate to Google Cloud VMware Engine
                  entries:
                    - title: Create a deployment plan using the migration advisor
                      url: /launch-migration-advisor-gcve.html
                - title: Migrate to Amazon EC2
                  entries:
                    - title: Create a deployment plan using the migration advisor
                      url: /launch-onboarding-advisor-native.html
                    - title: Deploy the recommended FSx for ONTAP file system
                      url: /deploy-fsx-file-system-native.html
                - title: Migrate to VMware Cloud on AWS
                  entries:
                    - title: Create a deployment plan using the migration advisor
                      url: /launch-onboarding-advisor.html
                    - title: Deploy the recommended FSx for ONTAP file system
                      url: /deploy-fsx-file-system.html
                    - title: Connect FSx for ONTAP to VMware Cloud on AWS
                      url: /connect-sddc-to-fsx.html
                    - title: Migrate your data to the new infrastructure
                      url: /migrate-data.html
                - title: Administer and monitor
                  entries:
                    - title: Configuration analysis for EVS configurations
                      url: /configuration-analysis.html
                    - title: Implement well-architected EVS configurations
                      url: /view-evs-well-architected.html
    - title: Google Cloud NetApp Volumes
      entries: 
        - title: Learn about Google Cloud NetApp Volumes
          url: /gcnv/learn-about-gcnv.html
        - title: Quick start for Google Cloud NetApp Volumes
          url: /gcnv/quick-start-gcnv.html
        - title: Add Google Cloud NetApp Volumes credentials
          url: /gcnv/add-credentials-gcnv.html
        - title: Configuration analysis for NetApp Volumes
          url: /gcnv/configuration-analysis-gcnv.html
        - title: Improve storage pool configurations
          url: /gcnv/improve-configurations.html
    - title: Oracle Cloud Infrastructure Storage with NetApp
      entries:
        - title: Learn about Oracle Cloud Infrastructure Storage with NetApp
          url: learn-about-ocsn.html
        - title: Quick start for Oracle Cloud Infrastructure Storage with NetApp
          url: quick-start-ocsn.html  
        - title: Add Oracle Cloud Infrastructure Storage with NetApp credentials
          url: add-credentials-ocsn.html
        - title: Discover Oracle Cloud Infrastructure Storage with NetApp systems
          url: create-discover-systems-ocsn.html
        - title: Connect to an Oracle Cloud Infrastructure Storage with NetApp system
          url: connect-to-system-ocsn.html
        - title: Permissions reference for Oracle Cloud Infrastructure Storage with NetApp
          url: permissions-reference-ocsn.html
    - title: Administer Workload Factory
      entries:
        - title: Manage service accounts
          url: /administer/manage-service-accounts.html
        - title: Build and operate well-architected workloads
          url: /administer/well-architected-workloads.html  
        - title: Configure notifications
          url: /administer/configure-notifications.html
        - title: Monitor operations with Tracker
          url: /administer/monitor-operations.html
        - title: Manage links
          url: /administer/manage-links.html     
        - title: Manage AI features
          url: /administer/manage-genai-features.html
        - title: Custom dashboards
          entries:
            - title: Learn about custom dashboards
              url: /administer/learn-custom-dashboards.html
            - title: Create a custom dashboard
              url: /administer/create-custom-dashboard.html
            - title: Manage custom dashboards
              url: /administer/manage-custom-dashboards.html
            - title: Troubleshoot custom dashboards
              url: /administer/troubleshoot-custom-dashboards.html
        - title: Automate tasks using Codebox
          entries:
            - title: Learn about Codebox
              url: /administer/codebox-automation.html
            - title: Use Codebox to generate code
              url: /administer/use-codebox.html
        - title: Use CloudShell
          url: /administer/use-cloudshell.html
        - title: Remove credentials
          url: /administer/manage-credentials.html 
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /support-registration.html
        - title: Get help
          url: /get-help.html     
    - title: Legal notices
      url: /legal-notices.html

product-family:
  name: NetApp Data Services
  repo: data-services-family