settings:
  name: Workload Factory for NetApp Console
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"  
  release_notes_autogen:
    release_notes_repo: console-relnotes
sidebar: 
  entries:
    - title: Workload Factory for NetApp Console
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Known limitations
          url: /known-limitations.html
    - title: Get started
      entries:
        - title: Learn about Workload Factory in NetApp Console
          url: /setup/learn-workload-factory.html
        - title: Quick start
          url: /setup/quick-start.html
        - title: Sign up and log in to Workload Factory
          url: /setup/sign-up-log-in-saas.html 
        - title: Learn about links
          url: /setup/links-overview.html
        - title: Learn about permissions
          url: /setup/learn-about-permissions.html
    - title: Amazon FSx for NetApp ONTAP
      entries:
        - title: Use FSx for ONTAP for storage workloads
          entries: 
            - title: Learn about FSx for ONTAP
              url: /fsx-storage/learn-fsx-ontap-fsx.html
            - title: Explore savings
              url: /fsx-storage/explore-savings-fsx.html
            - title: Create storage resources
              entries: 
                - title: Create or discover an FSx for ONTAP file system
                  url: /fsx-storage/create-discover-systems-fsx.html
                - title: Create a storage VM
                  url: /fsx-storage/create-storage-vm-fsx.html
                - title: Create a volume
                  url: /fsx-storage/create-volume-fsx.html
                - title: Create an igroup
                  url: /fsx-storage/create-igroup-fsx.html
                - title: Create a block device  
                  url: /fsx-storage/create-block-device-fsx.html
            - title: Learn about links
              url: /fsx-storage/links-overview-fsx.html
            - title: Discover and view cache volumes
              url: /fsx-storage/discover-cache-volumes-fsx.html
            - title: Access your data
              url: /fsx-storage/access-data-fsx.html
        - title: Protect your data
          entries:
            - title: Data protection overview 
              url: /fsx-storage/data-protection-overview-fsx.html
            - title: Use snapshots to protect data
              entries: 
                - title: Use snapshots to protect data
                  url: /fsx-storage/use-snapshots-fsx.html
                - title: Manage snapshot policies
                  url: /fsx-storage/manage-snapshot-policy-fsx.html
                - title: Manage snapshots
                  url: /fsx-storage/manage-snapshots-fsx.html    
            - title: Use backups to object storage
              url: /fsx-storage/use-backups-fsx.html
            - title: Use replication to protect data
              entries: 
                - title: Replicate data
                  url: /fsx-storage/create-replication-fsx.html
                - title: Replicate on-premises ONTAP data to FSx for ONTAP
                  url: /fsx-storage/use-onprem-data-fsx.html              
                - title: Replicate a storage VM to another file system
                  url: /fsx-storage/replicate-svm-to-file-system-fsx.html              
                - title: Track replication delays
                  url: /fsx-storage/track-replication-delays-fsx.html  
                - title: Manage replication relationships
                  url: /fsx-storage/manage-replication-fsx.html  
            - title: Protect data with Autonomous Ransomware Protection
              url: /fsx-storage/ransomware-protection-fsx.html   
            - title: Clone a volume
              url: /fsx-storage/clone-volume-fsx.html  
            - title: Create a cyber vault to protect data
              url: /fsx-storage/create-cyber-vault-fsx.html  
        - title: Manage FSx for ONTAP in Workload Factory
          entries:
            - title: Analyze FSx for ONTAP EMS events      
              url: /fsx-storage/analyze-events-fsx.html
            - title: Implement file system best practices
              entries: 
                - title: Configuration analysis for FSx for ONTAP
                  url: /fsx-storage/configuration-analysis-fsx.html
                - title: Implement well-architected file system configurations
                  url: /fsx-storage/improve-configurations-fsx.html 
            - title: Track and analyze FSx for ONTAP costs
              url: /fsx-storage/track-costs-fsx.html           
            - title: Manage volumes
              entries:  
                - title: Manage volume capacity
                  url: /fsx-storage/manage-volume-capacity-fsx.html
                - title: Set volume latency thresholds
                  url: /fsx-storage/set-volume-latency-thresholds-fsx.html
                - title: Manage volume settings
                  url: /fsx-storage/manage-volume-settings-fsx.html  
                - title: Manage cache volumes
                  url: /fsx-storage/manage-cache-volumes-fsx.html
                - title: Change a tiering policy
                  url: /fsx-storage/change-tiering-policy-fsx.html   
                - title: Manage NFS export policies
                  url: /fsx-storage/manage-nfs-export-policy-fsx.html  
                - title: Manage SMB/CIFS shares
                  url: /fsx-storage/manage-cifs-share-fsx.html 
                - title: Manage S3 access points 
                  entries: 
                    - title: Create and attach S3 access points
                      url: /fsx-storage/create-s3-access-points-fsx.html
                    - title: Edit S3 access points
                      url: /fsx-storage/edit-s3-access-points-fsx.html
                    - title: Set up the journal table infrastructure
                      url: /fsx-storage/setup-journal-table-fsx.html
                    - title: View details about S3 access points
                      url: /fsx-storage/view-s3-details-fsx.html
                    - title: Delete S3 access points
                      url: /fsx-storage/delete-s3-access-points-fsx.html           
                - title: Split a cloned volume
                  url: /fsx-storage/split-cloned-volume-fsx.html    
                - title: Delete a volume
                  url: /fsx-storage/delete-volume-fsx.html
            - title: Manage block storage
              entries:
                - title: Manage block storage
                  url: /fsx-storage/manage-block-storage-fsx.html
                - title: Apply tags to block devices
                  url: /fsx-storage/apply-block-device-tags-fsx.html  
            - title: Manage file systems
              entries: 
                - title: Adjust file system capacity
                  url: /fsx-storage/adjust-file-system-capacity-fsx.html
                - title: Manage file system settings
                  url: /fsx-storage/manage-file-system-settings-fsx.html
                - title: Provision IOPS for a file system
                  url: /fsx-storage/provision-iops-fsx.html              
                - title: Delete a file system
                  url: /fsx-storage/delete-file-system-fsx.html
            - title: Manage storage VMs
              entries: 
                - title: Manage storage VM settings
                  url: /fsx-storage/manage-svm-settings-fsx.html
                - title: Delete a storage VM 
                  url: /fsx-storage/delete-svm-fsx.html
            - title: Monitor operations with Tracker
              url: /fsx-storage/monitor-operations-fsx.html       
        - title: Use FSx for ONTAP for database workloads
          entries:
            - title: Learn about Workload Factory for Databases
              url: /fsx-databases/learn-about-databases-fsx.html
            - title: Quick start for Workload Factory for Databases
              url: /fsx-databases/quick-start-databases-fsx.html
            - title: Explore savings
              url: /fsx-databases/explore-savings-fsx-databases.html
            - title: Known limitations for Workload Factory for Databases
              url: /fsx-databases/known-limitations-fsx-databases.html
            - title: Create database resources
              entries:
                - title: Create Microsoft SQL Server    
                  url: /fsx-databases/create-sql-database-server-fsx.html
                - title: Create PostgreSQL server
                  url: /fsx-databases/create-postgresql-server-fsx.html  
                - title: Create a database
                  url: /fsx-databases/create-database.html 
                - title: Create a sandbox clone 
                  url: /fsx-databases/create-sandbox-clone.html                   
            - title: Manage resources
              entries: 
                - title: Resource management
                  url: /fsx-databases/manage-resources-fsx.html
                - title: Register resources
                  url: /fsx-databases/register-instance.html
                - title: Manage database clones
                  url: /fsx-databases/manage-clones-fsx.html                               
                - title: Deregister resources
                  url: /fsx-databases/deregister-instance.html                                               
            - title: Protect, monitor, and optimize database resources
              entries:
                - title: Analyze error logs
                  url: /fsx-databases/analyze-error-logs-fsx.html  
                - title: Implement configuration best practices
                  entries: 
                    - title: Configuration analysis for Databases
                      url: /fsx-databases/optimize-overview.html  
                    - title: Implement well-architected database configurations   
                      url: /fsx-databases/optimize-configurations.html  
                - title: Monitor database jobs
                  url: /fsx-databases/monitor-databases.html                          
                - title: Protect SQL Server database resources
                  url: /fsx-databases/protect-sql-server-fsx.html
        - title: Use FSx for ONTAP for EDA workloads
          entries:   
             - title: Learn about NetApp Workload Factory for EDA
               url: /learn-eda.html 
             - title: Quick start
               url: /quick-start-eda.html
             - title: Requirements
               url: /requirements-eda.html
             - title: EDA storage overview
               entries:
                 - title: Learn about the Overview dashboard
                   url: /learn-overview-dashboard.html
                 - title: Activate the Overview dashboard
                   url: /task-activate-overview-dashboard.html
                 - title: Use the Overview dashboard
                   url: /task-use-overview-dashboard.html
             - title: Project usage analysis
               entries:
                 - title: Learn about the Projects dashboard
                   url: /learn-project-dashboard.html
                 - title: Configure the Projects dashboard
                   url: /task-configure-project-dashboard.html
                 - title: Use the Projects dashboard
                   url: /task-use-project-dashboard.html
             - title: Use Perforce integration
               entries: 
                  - title: Learn about Perforce integration
                    url: /learn-eda-workloads.html
                  - title: Manage projects
                    url: /manage-projects.html
                  - title: Manage project versions
                    url: /version-projects.html
                  - title: Create a workspace
                    url: /create-workspaces.html
                  - title: Automate with Codebox
                    url: /automate-codebox.html
                  - title: Integrate with Perforce
                    url: /integrate-perforce.html
        - title: Use FSx for ONTAP for VMware workloads
          entries:                   
            - title: Learn about NetApp Workload Factory for VMware
              url: /learn-about-vmware-workloads.html
            - title: Quick start for migrating to Amazon EVS
              url: /quick-start-evs.html        
            - title: Quick start for migrating to Amazon EC2
              url: /quick-start-native.html
            - title: Quick start for migrating to VMware Cloud on AWS
              url: /quick-start.html
            - title: Quick start for migrating to Google Cloud VMware Engine
              url: /quick-start-gcve.html
            - title: Explore the VMware planning center
              url: /explore-planning-center.html
            - title: Use the VMware planning center
              entries:
                - title: Upload VM inventory data
                  url: /upload-vm-inventory.html
                - title: Migrate to Amazon Elastic VMware Service
                  entries:
                    - title: Explore savings
                      url: /calculate-evs-savings.html
                    - title: Manually create a deployment plan
                      url: /launch-migration-advisor-evs-manual.html
                    - title: Create a deployment plan using the migration advisor
                      url: /launch-migration-advisor-evs.html
                    - title: Deploy the recommended FSx for ONTAP file system
                      url: /deploy-fsx-file-system-evs.html
                - title: Migrate to Google Cloud VMware Engine
                  entries:
                    - title: Create a deployment plan using the migration advisor
                      url: /launch-migration-advisor-gcve.html
                - title: Migrate to Amazon EC2
                  entries:
                    - title: Create a deployment plan using the migration advisor
                      url: /launch-onboarding-advisor-native.html
                    - title: Deploy the recommended FSx for ONTAP file system
                      url: /deploy-fsx-file-system-native.html
                - title: Migrate to VMware Cloud on AWS
                  entries:
                    - title: Create a deployment plan using the migration advisor
                      url: /launch-onboarding-advisor.html
                    - title: Deploy the recommended FSx for ONTAP file system
                      url: /deploy-fsx-file-system.html
                    - title: Connect FSx for ONTAP to VMware Cloud on AWS
                      url: /connect-sddc-to-fsx.html
                    - title: Migrate your data to the new infrastructure
                      url: /migrate-data.html
                - title: Administer and monitor
                  entries:
                    - title: Configuration analysis for EVS configurations
                      url: /configuration-analysis.html
                    - title: Implement well-architected EVS configurations
                      url: /view-evs-well-architected.html
        - title: Reference
          entries: 
            - title: Performance for FSx for ONTAP
              url: /fsx-storage/performance-reference-fsx.html
            - title: Security for FSx for ONTAP
              url: /fsx-storage/security-reference-fsx.html   
    - title: Google Cloud NetApp Volumes
      entries: 
        - title: Learn about Google Cloud NetApp Volumes
          url: /gcnv/learn-about-gcnv.html
        - title: Quick start for Google Cloud NetApp Volumes
          url: /gcnv/quick-start-gcnv.html
        - title: Add Google Cloud NetApp Volumes credentials
          url: /gcnv/add-credentials-gcnv.html
        - title: Configuration analysis for NetApp Volumes
          url: /gcnv/configuration-analysis-gcnv.html
        - title: Improve storage pool configurations
          url: /gcnv/improve-configurations.html
    - title: Oracle Cloud Infrastructure Storage with NetApp
      entries:
        - title: Learn about Oracle Cloud Infrastructure Storage with NetApp
          url: /ocsn/learn-about-ocsn.html
        - title: Quick start for Oracle Cloud Infrastructure Storage with NetApp
          url: /ocsn/quick-start-ocsn.html  
        - title: Add Oracle Cloud Infrastructure Storage with NetApp credentials
          url: /ocsn/add-credentials-ocsn.html
        - title: Discover Oracle Cloud Infrastructure Storage with NetApp systems
          url: /ocsn/create-discover-systems-ocsn.html
        - title: Connect to an Oracle Cloud Infrastructure Storage with NetApp system
          url: /ocsn/create-link-ocsn.html
        - title: Permissions reference for Oracle Cloud Infrastructure Storage with NetApp
          url: /ocsn/permissions-ocsn.html
    - title: Administer Workload Factory
      entries:
        - title: Manage service accounts
          url: /administer/manage-service-accounts.html
        - title: Build and operate well-architected workloads
          url: /administer/well-architected-workloads.html  
        - title: Configure notifications
          url: /administer/configure-notifications.html
        - title: Monitor operations with Tracker
          url: /administer/monitor-operations.html
        - title: Manage links
          url: /administer/manage-links.html     
        - title: Manage AI features
          url: /administer/manage-genai-features.html
        - title: Custom dashboards
          entries:
            - title: Learn about custom dashboards
              url: /administer/learn-custom-dashboards.html
            - title: Create a custom dashboard
              url: /administer/create-custom-dashboard.html
            - title: Manage custom dashboards
              url: /administer/manage-custom-dashboards.html
            - title: Troubleshoot custom dashboards
              url: /administer/troubleshoot-custom-dashboards.html
        - title: Automate tasks using Codebox
          entries:
            - title: Learn about Codebox
              url: /administer/codebox-automation.html
            - title: Use Codebox to generate code
              url: /administer/use-codebox.html
        - title: Use CloudShell
          url: /administer/use-cloudshell.html
        - title: Remove credentials
          url: /administer/manage-credentials.html 
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /support-registration.html
        - title: Get help
          url: /get-help.html     
    - title: Legal notices
      url: /legal-notices.html

product-family:
  name: NetApp Data Services
  repo: data-services-family