---
sidebar: sidebar
permalink: fsx-storage/create-discover-systems-fsx.html
keywords: Amazon FSx for NetApp ONTAP, fsx, volumes, create system, delete system, access key, secret key, region, availability zones, discover, storage capacity, iops, throughput, security group, security, NetApp Console
summary: "Create or discover cloud storage systems to add and manage volumes and additional data services from the NetApp Console."
---
= Create or discover cloud storage systems in NetApp Console
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Create or discover cloud storage systems to add and manage volumes and additional data services from the NetApp Console.

== Create a storage system

The first step is to create a storage system. If you already created a storage system in your cloud provider's console, you can <<Discover an existing cloud storage system,discover it using the NetApp Console>>.

.About this task
A storage VM is created when you create a file system. 

.Before you begin
Before creating your FSx for ONTAP file system, you will need:

* The ARN of an IAM role that gives Workload Factory the permissions needed to create an FSx for ONTAP file system. link:permissions-fsx.html[Learn how to grant permissions to an AWS account^].

* The region and VPC information for where you will create the FSx for ONTAP instance.

== Create an FSx for ONTAP file system
You can create an FSx for ONTAP file system using _Quick create_ or _Advanced create_. You can also use the following tools available in the Codebox: REST API, CloudFormation, and Terraform. link:use-codebox.html#how-to-use-codebox[Learn how to use Codebox for automation^]. 

NOTE: When using Terraform from Codebox, the code you copy or download hides `fsxadmin` and `vsadmin` passwords. You'll need to re-enter the passwords when you run the code.  

[role="tabbed-block"]
====

.Quick create
--
Quick create enables you to use a recommended best-practice configuration. You can change most settings after you create an FSx for ONTAP file system. 

.Steps
. From the NetApp Console menu, select *Storage* and then *Management*. 
. Select *Add system* from the Systems page. 
. Select *Amazon Web Services* as the location, and then select *Add new* for Amazon FSx for NetApp ONTAP. 
include::_include/create-file-system-quick.adoc[]

.Result
If you created the file system, the new FSx for ONTAP configuration appears on the Systems page. 

You can manage your FSx for ONTAP file systems in several ways, such as from Workloads in the NetApp Console, using ONTAP System Manager, and using AWS CloudFormation.
--

.Advanced create
--
With Advanced create, you set all of the configuration options, including availability, security, backups, and maintenance. 

.Steps
. From the NetApp Console menu, select *Storage* and then *Management*. 
. Select *Add system* from the Systems page. 
. Select *Amazon Web Services* as the location, and then select *Add new* for Amazon FSx for NetApp ONTAP. 
include::_include/create-file-system-advanced.adoc[]

.Result

If you created the file system, the new FSx for ONTAP configuration appears on the Systems page. 

You can manage your FSx for ONTAP file systems in several ways, such as from Workloads in the NetApp Console, using ONTAP System Manager, and using AWS CloudFormation.
--

====


== Discover an existing cloud storage system 

If you previously provided your credentials for your cloud storage provider in Workload Factory, you can automatically discover your storage systems from the Discoverable systems page. You can also review available data services. 

.About this task
You can discover a cloud storage system only once within an account and attach it to one workspace. The storage system can later be removed and re-associated to a different workspace.

.Steps

. From the NetApp Console menu, select *Storage*, then *Management*, and then *Discoverable systems*. 

. The count of discovered cloud storage systems displays. Select *Discover*.  

. Select one or more storage systems and select *Discover* to add them to the Systems page. 

[NOTE]
===============================
* If you select an un-named storage system, you will receive a prompt to enter a name for the system.

* If you select a storage system that doesn't have the credentials required to manage it from the Console, you'll receive a prompt to select credentials with the required permissions. 

* The following regions aren't supported for discovery: China regions, GovCloud (US) regions, Secret Cloud, and Top Secret Cloud.
===============================

.Result

The Console displays your discovered system on the Systems page. You can manage your storage systems in several ways, such as from Workloads in the NetApp Console and using ONTAP System Manager or using your cloud provider's storage management tools. 