---
sidebar: sidebar
permalink: learn-about-ocsn.html
keywords: Oracle Cloud Infrastructure Storage with NetApp, Oracle Cloud storage, storage, ocsn
summary: "Oracle Cloud Infrastructure Storage with NetApp (OCSN) is a fully managed service allowing customers to create and manage storage pools as the storage backend for your workloads within Workload Factory." 
---
= Learn about Oracle Cloud Infrastructure Storage with NetApp in NetApp Workload Factory
:icons: font
:imagesdir: ./media/

[.lead]
Oracle Cloud Infrastructure Storage with NetApp (OCSN) is a fully managed, cloud-based data storage service that provides advanced data management capabilities and highly scalable performance. OCSN allows you to create and manage storage pools as the storage backend for all your workloads within NetApp Workload Factory. 

OCSN provides the same features, performance, and administrative capabilities NetApp customers use on premises today, with the simplicity, agility, security, and scalability of a native Oracle Cloud service.

OCSN is the _Storage_ component in Workload Factory.

== Features
OCSN offers the following features:

* *Fully-managed service*: provides a fully-managed service integrated with the Workload Factory console. 
* *High availability*: provides high availability for each OCSN storage pool, supporting Single and Multiple Availability Zones deployments. 
* *Automated snapshots*: protects data with automated, efficient snapshots, which are near instantaneous, space efficient point-in-time read-only copies of the storage pool or volumes. 
* *Volume replication*: provides disaster recovery with cross-region replication across Oracle Cloud Infrastructure. 
* *Efficient backups*: adds an extra layer of protection with a copy of the data in another region for emergencies.
* *Fast cloning*: accelerates application development with fast cloning.
* *Multi-protocol support*: supports Network File System (NFS), Server Message Block (SMB), and Internet Small Computer Systems Interface (iSCSI) protocols. 
* *High throughput*: delivers high throughput performance to ensure low latencies for workloads running on top of OCSN file systems. 
* *In-memory cache and NVMe cache*: includes a unique in-memory cache and NVMe cache, which boosts the performance of frequently accessed data.
* *Hundreds of thousands of IOPS*: provides hundreds of thousands of IOPS with SSD disks, ensuring that your storage and workloads receive timely results.
* *Thin Provisioning*: allows capacity provisioning in advance, saving costs until more capacity is needed.  
* *Data deduplication and compression*: removes duplicate data and compresses data to reduce the amount of physical storage that is required for OCSN file systems resulting in cost savings. 
* *Data tiering*: allows storage cost reduction by moving less frequently accessed data from the primary, high performance SSD storage tier to the secondary capacity pool storage tier. 

//Cross-repo include for Tools section
include::https://raw.githubusercontent.com/NetAppDocs/workload-family/main/_include/learn-about-tools.adoc[]

== Regions
Workload Factory is supported in all commercial regions where OCSN is supported. link:https://www.oracle.com/cloud/public-cloud-regions/[View supported Oracle public cloud regions.^]
 
The following Oracle regions aren't supported:
 
??

== Getting help
Oracle Cloud Infrastructure Storage with NetApp (OCSN) is an Oracle Cloud first-party solution. For questions or technical support issues associated with your OCSN file system, infrastructure, or any solution using this service, use the Support Center in your Oracle Cloud Console to open a support case with Oracle Cloud. Select the “OCSN” service and appropriate category. Provide the remaining information required to create your Oracle Cloud support case.

For general questions about Workload Factory or Workload Factory applications and services, refer to link:get-help.html[Get help for OCSN for Workload Factory].