---
sidebar: sidebar
permalink: fsx-eda/requirements.html
keywords: Builders, FSx, project, projects. eda, electronic design automation, requirements, setup, Workload Factory
summary: "Ensure that NetApp Workload Factory and AWS are set up properly before you begin using NetApp Workload Factory for EDA. This includes having your AWS log in credentials, a deployed FSx for ONTAP file system, and more."
---
= Workload Factory for EDA requirements
:icons: font
:imagesdir: ../media/

[.lead]
Ensure that NetApp Workload Factory and AWS are set up properly before you use NetApp Workload Factory for EDA. This includes having your AWS log in credentials, a deployed FSx for ONTAP file system, and more.

Workload Factory login and account::
You'll need to link:../setup/sign-up-and-log-in.html[sign up and log in to NetApp Console.] 

AWS credentials and permissions::
You need to add AWS credentials to Workload Factory with read/write permissions, which means you'll be using Workload Factory in _read/write_ mode for EDA.

_Basic_ mode and _Read-only_ mode permissions are not supported at this time.

NOTE: AWS credentials are also required to use the latency monitoring feature, which collects CloudWatch metrics for volume performance analysis. To receive notifications for latency events, configure notification preferences in Workload Factory settings. Optional AI analysis for complex latency scenarios is available when NetApp-managed AI analysis is enabled. link:learn-latency-monitoring.html[Learn about latency monitoring].

link:../fsx-storage/add-credentials.html[Learn how to add AWS credentials to Workload Factory.]

FSx for ONTAP file system::
You need a minimum of one FSx for ONTAP file system:

* The file system will be used by EDA to store the projects and workspaces that you create. 
+
This FSx for ONTAP file system must use FlexVol volumes. FlexGroup volumes are not supported.

* You'll need to know the AWS region, VPC, and subnet where the AWS FSx for ONTAP file system resides.

* You'll need at least one volume in the file system with the following configuration:
** The volume must be configured as an NFS share.
** The file system must be configured with a link. link:../setup/links-overview.html[Learn more about links].

* You'll need to consider the tag key/value pairs that you want to apply to the AWS resources that are part of this deployment (optional).
+
link:../fsx-storage/create-discover-systems.html[Learn how to discover or create FSx for ONTAP file systems.]

