---
sidebar: sidebar
permalink: admin/links-overview.html
keywords: links, accounts, connectivity, 
summary: "A Workload Factory link creates a trust relationship and connectivity between a Workload Factory account and one or more cloud storage systems."
---
= Learn about NetApp Workload Factory links
:icons: font
:imagesdir: ../media/

[.lead]
A NetApp Workload Factory link creates a trust relationship and connectivity between a Workload Factory account and one or more cloud storage systems. This allows you to monitor and manage certain storage system features directly from the ONTAP REST API calls that are not available through the your cloud provider API.

You don't need a link to get started with Workload Factory, but in some cases you'll need to create a link to unlock all Workload Factory features and workload capabilities. 

== Why links are beneficial
Links are beneficial because they allow Workload Factory to perform operations that are not natively available through your cloud provider's API. Links enable advanced ONTAP capabilities and automation, which enhance the management of your cloud storage systems.

Here are some benefits of using links:
 
* The link enables the NetApp Console to send ONTAP commands directly to your cloud storage system, bringing advanced ONTAP features beyond what your cloud provider offers natively.
* Links leverage remote serverless functions to execute code in response to events. This serverless approach removes the dependency of an instance running in your VPC.

== How links work

Links leverage remote serverless compute services, such as AWS Lambda and Oracle Cloud Infrastructure Functions. The services execute code in response to events and automatically manage the computing resources required by that code. The links that you create are part of your NetApp account and they are associated with the corresponding cloud provider account.

After creating a link, you can associate it with one, or many, cloud storage systems. Each cloud storage system can be associated only to one link in the same NetApp account. If you have multiple NetApp accounts, a single cloud storage system can be associated with additional links under different NetApp accounts.

You create and associate links from the Links page in the NetApp Console for your cloud storage systems.

You can authenticate links using credentials stored in the Workload Factory credentials service or with your cloud provider's credential service. Workload Factory doesn't support changing authentication modes.

== Costs

Each transaction that your cloud provider's serverless compute service performs incurs a charge. Because it acts as a proxy between the two systems, there is a charge when the service sends a request to the ONTAP REST API on a file system, and when it sends the response back to Workload Factory.

link:https://aws.amazon.com/lambda/pricing/[Learn more about the costs related to using AWS Lambda^]
link:https://www.oracle.com/cloud/cloud-native/functions/[Learn more about the costs related to using Oracle Cloud Infrastructure Functions^]

== When a link is required

Workload Factory requires a link to display some information and to perform some tasks. If you attempt to perform an operation that requires a link and you haven't associated a link with the cloud storage system, Workload Factory notifies you that the operation requires a link. 

The features that require a link include:

* Well-architected status of cloud storage system configurations for proactive maintenance, reliability, and cost-performance optimization
* ONTAP EMS event monitoring and alerting
* NetApp Autonomous Ransomware Protection (ARP/AI)
* Enhanced holistic capacity observability across cloud storage systems
* Volume and storage VM data replication, management, and monitoring
* SMB/CIFS shares and NFS export policy provisioning and management
* Management of iSCSI volumes on a cloud storage system
* Creation and management of snapshot policies for custom protection SLA
* Inode management enhancements for automatic capacity management
* Volume autogrow for elastic scaling
* Clone creation and management, for instant, in-place, data cloning
* Displaying additional metrics directly from your cloud storage system such as the system version
* Displaying storage VM and cluster LIF details including roles, endpoints, nodes, IP addresses, and status

== Related information
Learn how to create and associate links for:

* link:fsx-storage/create-link-fsx.adoc[Amazon FSx for NetApp ONTAP]
* link:ocsn/create-link-ocsn.adoc[OCI NetApp Storage Service]