---
sidebar: sidebar
permalink: setup/quick-start.html
keywords: quick start
summary: "Get started with Workload Factory by signing up and creating an account in NetApp Console and adding cloud provider credentials so that Workload Factory can manage your resources directly and optimize your workloads."
---
= Quick start for NetApp Workload Factory
:icons: font
:imagesdir: ../media/

[.lead]
NetApp Workload Factory is accessible to users as a cloud data service from NetApp Console. Get started with Workload Factory by signing up and creating an account in NetApp Console and adding cloud provider credentials so that Workload Factory can manage your resources directly and optimize your workloads.

Before you get started, you should have an understanding of link:learn-about-workload-factory.html[Workload Factory].

== Sign up and log in to Workload Factory from NetApp Console

link:sign-up-and-log-in.html[Sign up and log in to Workload Factory from NetApp Console]

Next, select the *Quick start* link for your cloud provider to get started.

== Get started with Amazon FSx for NetApp ONTAP
link:../fsx-storage/quick-start-fsx.html[Quick start for Amazon FSx for NetApp ONTAP]

== Get started with OCI NetApp Storage Service
link:../oci/quick-start-oci.html[Quick start for OCI NetApp Storage Service]

== Get started with Google Cloud NetApp Volumes
link:../gcnv/quick-start-gcnv.html[Quick start for Google Cloud NetApp Volumes]

