---
sidebar: sidebar
permalink: setup/quick-start.html
keywords: quick start
summary: Get started with Workload Factory by preparing networking for the Workload Factory console, signing up and creating an account, and adding credentials so that Workload Factory can manage AWS resources directly.
---
= Quick start for NetApp Workload Factory
:icons: font
:imagesdir: ../media/

[.lead]
Get started with NetApp Workload Factory by signing up and creating an account, adding credentials so that Workload Factory can manage your resources directly, and then optimize your workloads for your cloud provider.

NetApp Workload Factory is accessible to users as a cloud service from the web-based console. Before you get started, you should have an understanding of link:learn-about-workload-factory.html[Workload Factory].

Select the *Quick start* link for your cloud provider to get started: 

* link:fsx/quick-start-fsx.html[Quick start for Amazon FSx for NetApp ONTAP]
* link:oci/quick-start-oci.html[Quick start for Oracle Cloud Infrastructure Storage with NetApp]
* link:gcp/quick-start-gcp.html[Quick start for Google Cloud NetApp Volumes]

