---
sidebar: sidebar
permalink: setup/sign-up-and-log-in.html
keywords: sign up, signing up, sign in, signing in, login with netapp, log in with netapp, create account, account, log in with nss, nss, nss login
summary: Workload Factory is accessible from NetApp Console. When you get started with Workload Factory, your first step is to sign up using your existing NetApp Support Site credentials or by creating a NetApp cloud login.
---
= Sign up and log in to Workload Factory from NetApp Console
:icons: font
:imagesdir: ../media/ 

[.lead]
NetApp Workload Factory is accessible from NetApp Console. To use the Console, sign up or log in with your NetApp Support Site credentials, or create a NetApp Console login. If you are the first from your company to sign up, you create a new organization as the administrator. If your company already has an organization, sign up or log in with your existing NetApp Support Site credentials or company single-sign-on (SSO). 

== Sign up for NetApp Console as the initial organization administrator

If your company doesn't have a NetApp Console organization, sign up to create one. The first user becomes the organization administrator and manages user accounts and permissions. You can update roles and add more administrators later.

.Steps

. Open a web browser and go to the https://console.netapp.com[NetApp Console^].

. If you have a NetApp Support Site account, enter the email address associated with your account directly on the *Log in* page.
+
The Console signs you up as part of this initial login with your NetApp Support Site credentials.

. If you want to sign up by creating a Console login, select *Sign up*.

.. On the *Sign up* page, enter the required information and select *Next*.
+
NOTE: Only English characters are allowed in the sign up form.

.. Check your inbox for an email from NetApp that includes instructions to verify your email address.
+
Verify your email address to complete sign up.

. After you log in, review and accept the End User License Agreement.

. On the *Welcome* page, create an organization.

. Select *Let's Start*.

+ As a first-time user and organization administrator, you follow a guided process to add storage resources, create a Console agent, and more. link:https://docs.netapp.com/us-en/console-setup-admin/task-console-assistant.html[Learn about using the Console Assistant.^]

.Next steps
As an administrator, after you complete the steps included in the Console Assistant, you should plan your identity and access strategy, add users to your organization, and assign roles. link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-get-started.html[Learn about identity and access management for NetApp Console^]


== Sign up or login to NetApp Console when an organization already exists

If your company already has a NetApp Console organization, sign up or log in to access it. Your sign-up or log-in method depends on whether your company uses identity federation or has NetApp Support Site credentials. If not, create a NetApp Console log-in.

.Steps

. Open a web browser and go to the https://console.netapp.com[NetApp Console^].

. If you have a NetApp Support Site account or if your company has set up single sign-on (SSO), enter your associated email address or SSO credentials on the *Log in* page. Follow the prompts to complete login.
+
In both of these cases, you are signed up for the Console as part of this initial login.

. If you want to sign up by creating a Console login, select *Sign up*.

.. On the *Sign up* page, enter the required information and select *Next*.
+
NOTE: Only English characters are allowed in the sign up form.

.. Check your inbox for an email from NetApp that includes instructions to verify your email address.
+
Verify your email address to complete sign up.

. After you log in, review and accept the End User License Agreement.

. If the system prompts you to create an organization, close the dialog box and tell a Console admin so they can add you to your Console organization and give you access. link:https://docs.netapp.com/us-en/console-setup-admin/task-user-settings.html#contact-admin[Learn how to contact an organization administrator.^] 

.Next steps

You're now logged in and can start using Workload Factory to manage your storage systems and workloads. To get to Workload Factory, select *Workloads* from the main menu.


